namespace MongoDB.InMemory.ObjectModel.Enums
{
    internal enum PipelineOperator
    {
        AddFields,
        Bucket,
        BucketAuto,
        CollStats,
        Count,
        Facet,
        GeoNear,
        GraphLookup,
        Group,
        IndexStats,
        Limit,
        ListSessions,
        Lookup,
        Match,
        Merge,
        Out,
        PlanCacheStats,
        Project,
        Redact,
        ReplaceRoot,
        ReplaceWith,
        Sample,
        Search,
        Set,
        Skip,
        Sort,
        SortByCount,
        UnionWith,
        Unset,
        Pull,
        Push,
        Unwind
    }
}